# Admittance parameters for two mass damper systems
# (the arm and the platform) with params (mass_arm, damping_arm)
# and (mass_platform, damping_platform) respectively, connected by a
# spring-damper with parameters (damping_coupling, stiffness_coupling,
# equilibrium_point_spring)
mass_platform: [10,0,0,0,0,0,
                0,10,0,0,0,0,
                0,0,10,0,0,0,
                0,0,0,10000,0,0,
                0,0,0,0,10000,0,
                0,0,0,0,0,10000]
mass_arm: [20,0,0,0,0,0,
           0,20,0,0,0,0,
           0,0,20,0,0,0,
           0,0,0,5,0,0,
           0,0,0,0,5,0,
           0,0,0,0,0,0.7]
damping_coupling: [0,0,0,0,0,0,
                   0,0,0,0,0,0,
                   0,0,0,0,0,0,
                   0,0,0,0,0,0,
                   0,0,0,0,0,0,
                   0,0,0,0,0,0]
damping_platform: [50,0,0,0,0,0,
                   0,50,0,0,0,0,
                   0,0,50,0,0,0,
                   0,0,0,0,0,0,
                   0,0,0,0,0,0,
                   0,0,0,0,0,50]
damping_arm: [120,0,0,0,0,0,
              0,120,0,0,0,0,
              0,0,120,0,0,0,
              0,0,0,50,0,0,
              0,0,0,0,50,0,
              0,0,0,0,0,10]
stiffness_coupling: [50,0,0,0,0,0,
                     0,100,0,0,0,0,
                     0,0,50,0,0,0,
                     0,0,0,0,0,0,
                     0,0,0,0,0,0,
                     0,0,0,0,0,0]
equilibrium_point_spring: [0.1,0.4,0.5,-1.0,-1.5,-2.2]
